server:
  port: 8081

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: update  # in development (auto table create/modify)
      # ddl-auto: none  # in operation (manual sql management)
    show-sql: true